global:
  namespace: ns-data-scrapper

frontend:
  name: ns-data-scrapper
  port: 5000
  replicaCount: 1
  proxy:
    incomingPath: /data-scrapper-app/
    containerPath: ""
  image:
    repository: gt-build.hdap.gatech.edu/data-scrapper # TODO: update to gatech registry
    tag: latest
    pullPolicy: Always

database:
  #name is a DNS-1035 label and must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123')
  name: ds_db
  port: 5432
  replicaCount: 1
  image:
    repository: mariadb
    tag: latest
    pullPolicy: Always
  volumes:
    vol1: /var/lib/mysql/data
  env:
    MYSQL_ROOT_PASSWORD: abc123456