global:
  namespace: data-scraper

frontend:
  name: data-scraper
  port: 80
  replicaCount: 1
  proxy:
    incomingPath: /data-scraper/
    containerPath: ""
  image:
    repository: allenlsy/ds-data-scraper # TODO: update to gatech registry
    tag: latest
    pullPolicy: Always
