global:
  namespace: ns-data-scrapper

frontend:
  name: frontend
  port: 5000
  replicaCount: 1
  proxy:
    incomingPath: /data-scrapper-app/
    containerPath: "/"
  image:
    repository: gt-build.hdap.gatech.edu/data-scrapper
    tag: latest
    pullPolicy: Always

database:
  name: data-scrapper-db
  port: 3306
  replicaCount: 1
  image:
    repository: mariadb
    tag: latest
    pullPolicy: Always
  volumes:
    vol1: /var/lib/mysql/data
  env:
    MYSQL_ROOT_PASSWORD: abc123456
